### PR TITLE
Dbi<byte[]> suggestion

### PR DESCRIPTION
**Pull request by krisskross**
Related to discussion in #3

### CODE REVIEW

**Comment by krisskross** [comment]
We don't need a `Holder` class since the return value of `BufferProxy.out` can be used to achieve the same effect.

**Comment by krisskross** [comment]
As the number of `BufferProxy` implementations grow I think we should consider parameterizing tests for every implementation to achieve better test coverage instead of having separate incomplete tests. Not sure how but i'm sure we can do a better job here.

**Comment by krisskross** [comment]
Not sure how to get rid of the last PMD plugin failure.

```
[INFO] --- maven-pmd-plugin:3.6:cpd-check (config-pmd) @ lmdbjava ---
[INFO] CPD Failure: Found 32 lines of duplicated code at locations:
[INFO]     /home/travis/build/lmdbjava/lmdbjava/src/test/java/org/lmdbjava/CursorTest.java line 204
[INFO]     /home/travis/build/lmdbjava/lmdbjava/src/test/java/org/lmdbjava/CursorTest.java line 273
```

**Comment by benalexau** [comment]
Do you think we should keep the existing `Env.create()` method without the rename? It's just that way we don't break any existing users, it reduces the number of changed files in the commit, and it's consistent with the `DirectBuffer` support (ie passing the relevant `static final BufferProxy` to the `Env.create(BufferProxy)` method. It also "encourages" people to use the `ByteBuffer` proxy (as opposed the `ByteArrayProxy`), which is a good thing given the unavoidable copying costs of the byte array approach.

To overcome the PMD issue feel free to pop `<cpd.skip>true</cpd.skip>` into the Maven POM `<properties>` and that way CI will be happy for now. I agree we should parametrize the tests, but we should get your changes merged in first so that you don't have merge conflicts to be bothered with....

**Comment by krisskross** [comment]
Sorry for the late reply. Yes, i'll change `Env.create()` back to the way it was and add `<cpd.skip>true</cpd.skip>` into the Maven POM.

**Comment by benalexau** [comment]
> I think we should consider parameterizing tests for every implementation to achieve better test coverage instead of having separate incomplete tests. Not sure how but i'm sure we can do a better job here.

I've just implemented parameterized cursor tests in d81f0624eb010d06329fc6ba83df346f67eafaab.

**Comment by krisskross** [comment]
The failing test on appveyor is quite peculiar, since the test works fine on travis. Is there a way to tigger the build manually?

**Comment by benalexau** [comment]
The AppVeyor build failure was a puzzle to me as well. It worked fine on my 64-bit Windows VM.

I recall a past Windows issue was related to `Env` not being closed after the tests, and reaching what appeared to be a platform limit around the number of `Env`s and/or `Dbi`s. As such I reviewed the test cases and formally closed a good number of `Env`s where possible as part of commit 986340900e. I also reduced the allocated space for a test `Env` in 31174b3674c2909a9bf6ba31bbf93f2cc5c83dac.

I'm unsure what fixed it, but the AppVeyor test now passes.

**Comment by krisskross** [comment]
OK great that it works now!

**Pull request merged**
