### PR TITLE
segfaults after MDB_MAP_FULL as per issue #17

### PR DESCRIPTION
**Pull request by phraktle**
Let's see if this crashes on the integration servers (crashes locally ;)

### CODE REVIEW

**Comment by phraktle** [comment]
Hm, no crashes there. I'll do some digging into what's different about the environments...

**Comment by benalexau** [comment]
I'll hold-off merging this one until we figure out what's happening. It might also be desirable to use `@Test(expected = MapFullException.class)` and put it in `EnvTest` for long-term inclusion.

**Comment by phraktle** [comment]
Didn't notice that the test was not run during the build (only in my IDE) due to a naming convention. Having renamed it, it now crashes the JVM on the CI servers too.

**Comment by benalexau** [comment]
I've committed a patch that I think will solve this. Can you give it a try (maybe using the built snapshot or by making a small change to the PR to wake up the CI servers again)? I added a permanent `EnvTest.mapFull()` to avoid future regression.

**Comment by phraktle** [comment]
Thanks @benalexau, it looks like your patch has fixed the crash, the tests have passed (the build failed with irrelevant checkstyle errors).

**Comment by benalexau** [comment]
Great! Thanks for the problem report and testing. I'll cut an 0.0.3 release once ticket #18 is confirmed resolved.

**Pull request closed without merging**
